# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OneEighty' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OneEighty

  target 'OneEightyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OneEightyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  pod 'PageMenu'

end
